# Imports

In [2]:
# Dataframes
import pandas as pd

# Path
import os
data_path = os.path.join('..', 'data')

# JSON
import json

# Load Data

In [3]:
eval_2e5_best_overlap_masked_decoder = pd.read_csv(os.path.join('./Bart30_Mask10to100_TF90to0_Eval100_HumanCodonPrediction', 'bart30_evaluation_2e5_best_masked_decoder_overlap.csv'))

eval_2e5_best_overlap_masked_decoder['accuracy'].loc[:].mean()

np.float64(0.5195381761943917)

In [ ]:
ablation_eval_2e5_best_overlap_masked_decoder = pd.read_csv(os.path.join('./Ablation_2_Bart30_Mask10to100_TF90to0_HumanCodonPrediction_2e5_Eval100NTF', 'ablation2_bart30_evaluation_2e5_best_masked_decoder_overlap.csv'))

ablation_eval_2e5_best_overlap_masked_decoder['accuracy'].loc[:].mean()

np.float64(0.5164021253956869)

In [5]:
eval_2e5_best_overlap_masked_decoder['protein_len'].min()

np.int64(12)

In [3]:
len(eval_2e5_best_overlap_masked_decoder)

15976

In [11]:
eval_2e5_best_overlap = pd.read_csv(os.path.join('./Bart30_Mask10to100_TF90to0_WarmupTF_HumanCodonPrediction', 'bart30_evaluation_2e5_best_overlap.csv'))

eval_2e5_best_overlap['accuracy'].mean()

np.float64(0.5160168137300186)

In [23]:
eval_2e5_best_overlap = pd.read_csv('bart30_evaluation_2e5_best_overlap.csv')

eval_2e5_best_overlap['accuracy'].mean()

np.float64(0.5157426955652189)

In [ ]:
eval_2e5_best_0 = pd.read_csv("bart30_evaluation_2e5_best_14.csv")
eval_2e5_best_0['accuracy'].mean()

np.float64(0.48202481826545024)

In [6]:
eval_2e5_best_0 = pd.read_csv("bart30_evaluation_2e5_best_0.csv")
eval_2e5_best_0['accuracy'].mean()

np.float64(0.5142603721722682)

In [13]:
eval_2e5_best_avg_logits = pd.read_csv("bart30_evaluation_2e5_best_avg_logits.csv")
eval_2e5_best_avg_logits['accuracy'].loc[0].mean()

np.float64(0.472668810289389)

In [4]:
eval_3e5_best_accuracy_experiment = pd.read_csv('bart_30_evaluation_3e5_last_acc_exp_3.csv')
eval_3e5_best_accuracy_experiment['accuracy'].mean()

np.float64(0.5050696547436232)

In [5]:
eval_3e5_best_accuracy_experiment = pd.read_csv('bart_30_evaluation_3e5_last_acc_exp_1.csv')
eval_3e5_best_accuracy_experiment['accuracy'].mean()

np.float64(0.4941828524830478)

In [34]:
eval_3e5_best_accuracy_experiment = pd.read_csv('bart_30_evaluation_3e5_best_acc_exp.csv')
eval_3e5_best_accuracy_experiment['accuracy'][0]

np.float64(0.480171489817792)

In [2]:
eval_3e5_last_accuracy_experiment = pd.read_csv('bart_30_evaluation_3e5_last_acc_exp.csv')
eval_3e5_last_accuracy_experiment['accuracy'].mean()

np.float64(0.5145141134946879)

In [3]:
eval_3e5_last_accuracy_experiment[eval_3e5_last_accuracy_experiment['accuracy'].isna()]['accuracy'].mean()

nan

In [8]:
eval_3e5_last = pd.read_csv('bart_30_evaluation_3e5_best.csv')
eval_3e5_last['accuracy'][:].mean()

np.float64(0.49367938386240273)

In [6]:
eval_3e5_best = pd.read_csv('bart_30_evaluation_3e5_last.csv')
eval_3e5_best['accuracy'].mean()

np.float64(0.5008873480409191)

In [4]:
eval_1_5_e5_best = pd.read_csv('bart30_evaluation_1.5e5_best.csv')
eval_1_5_e5_last = pd.read_csv('bart30_evaluation_1.5e5_last.csv')
eval_2_e5_best = pd.read_csv('bart30_evaluation_2e5_best.csv')
eval_2_e5_last = pd.read_csv('bart30_evaluation_2e5_last.csv')

In [5]:
print(eval_1_5_e5_best['accuracy'].mean())
print(eval_1_5_e5_last['accuracy'].mean())
print(eval_2_e5_best['accuracy'].mean())
print(eval_2_e5_last['accuracy'].mean())

0.49992453268461196
0.4944174139911076
0.4984576044965763
0.49517389323903443

In [5]:
bart_lin_eval['accuracy'].mean()

np.float64(0.5008873480409191)

In [2]:
bart_pretrain_temp_results = pd.read_csv(os.path.join(data_path, 'bart_30_pretrain_evaluation_temp.csv'))

In [3]:
bart_pretrain_temp_results['accuracy'].mean()

np.float64(0.49326315866974263)

In [9]:
len(bart_pretrain_temp_results)

9501

In [4]:
bart_finetune_results = pd.read_csv(os.path.join(data_path, 'bart_30_finetune_evaluation.csv'))

In [5]:
bart_finetune_results['accuracy'].mean()

np.float64(0.49134886743800466)

## Use best model

In [ ]:
test_with_baseline = pd.read_pickle(os.path.join(data_path, '2_test_nn_with_baseline_50.pkl'))

bart_results = pd.read_csv(os.path.join('./Bart30_Mask10to100_TF90to0_Eval100_HumanCodonPrediction', 'bart30_evaluation_2e5_best_masked_decoder_overlap.csv'))
bart_ablation_results = pd.read_csv(os.path.join('./Ablation_2_Bart30_Mask10to100_TF90to0_HumanCodonPrediction_2e5_Eval100NTF', 'ablation2_bart30_evaluation_2e5_best_masked_decoder_overlap.csv'))

print(bart_results['accuracy'].mean())
print(bart_ablation_results['accuracy'].mean())

0.5195381761943917
0.5164021253956869

In [27]:
test_with_baseline.columns

Index(['cluster', 'length (aa)', 'query_gene', 'query_transcript', 'seq',
       'amino_acid_seq', 'median', 'subject_transcript', 'average_pident',
       'gene', 'transcript', 'median_float', 'mfc_prediction', 'mfc_accuracy',
       'mfb_prediction', 'mfb_accuracy', 'exp_harmonized_prediction',
       'exp_harmonized_accuracy'],
      dtype='object')

In [28]:
bart_results.head()

,inx,transcript,protein_len,protein_AAs,protein_codons,predicted_codons,entropy,num_of_correct_predicted_codons,cross_entropy_loss,perplexity,accuracy
0,0,ENST00000396097,933,MSRVQTMNYVGQLAGQVFVTVKELYKGLNPATLSGCIDIIVIRQPN...,ATG AGC AGA GTG CAG ACC ATG AAT TAC GTG GGG CA...,ATG AGC AGA GTG CAG ACC ATG AAC TAT GTG GGG CA...,1.050366,472,1.074200,2.927649,0.505895
1,1,ENST00000634606,250,MWLDHRAVSQVNRINETKHSVLQYVGGVMSVEMQAPKLLWLKENLR...,ATG TGG CTG GAC CAT CGA GCA GTC AGT CAA GTT AA...,ATG TGG CTG GAC CAC AGA GCT GTG TCT CAA GTG AA...,1.038634,117,1.113958,3.046392,0.468000
2,2,ENST00000416623,464,MATFPCQLCGKTFLTLEKFTIHNYSHSRERPYKCVQPDCGKAFVSR...,ATG GCC ACG TTC CCC TGC CAG TTA TGT GGC AAG AC...,ATG GCC ACC TTT CCC TGC CAG CTC TGT GGG AAG AC...,1.010883,263,1.012083,2.751327,0.566810
3,3,ENST00000550383,433,MGQAGCKGLCLSLFDYKTEKYVIAKNKKVGLLYRLLQASILAYLVV...,ATG GGG CAG GCG GGC TGC AAG GGG CTC TGC CTG TC...,ATG GGA CAG GCT GGC TGC AAA GGA CTC TGC CTG TC...,1.029038,257,1.012481,2.752422,0.593533
4,4,ENST00000690706,58,MAFWAGGSPSVVDYFPSEDFYRCGYCKNESGSRSNGMWAHSMTVQD...,ATG GCT TTC TGG GCG GGG GGT TCG CCC AGC GTC GT...,ATG GCC TTC TGG GCT GGA GGC TCT CCC TCT GTG GT...,0.950364,29,1.068339,2.910542,0.500000

# Merge Dataframes

In [6]:
bart_results['predicted_codons'] = bart_results['predicted_codons'].str.replace(' ', '')

bart_results = bart_results.drop(columns=['inx', 'protein_len', 'protein_AAs', 'protein_codons'])

bart_results.rename(columns={'accuracy': 'bart30_accuracy',
                             'entropy': 'bart30_entropy',
                             'predicted_codons': 'bart30_prediction',
                             'num_of_correct_predicted_codons': 'bart30_num_of_correct_predicted_codons',
                             'perplexity': 'bart30_perplexity',
                             'cross_entropy_loss': 'bart30_cross_entropy_loss'}, inplace=True)


bart_ablation_results['predicted_codons'] = bart_ablation_results['predicted_codons'].str.replace(' ', '')

bart_ablation_results = bart_ablation_results.drop(columns=['inx', 'protein_len', 'protein_AAs', 'protein_codons'])

bart_ablation_results.rename(columns={'accuracy': 'bart30_ablation_accuracy',
                             'entropy': 'bart30_ablation_entropy',
                             'predicted_codons': 'bart30_ablation_prediction',
                             'num_of_correct_predicted_codons': 'bart30_ablation_num_of_correct_predicted_codons',
                             'perplexity': 'bart30_ablation_perplexity',
                             'cross_entropy_loss': 'bart30_ablation_cross_entropy_loss'}, inplace=True)

In [7]:
test_with_results = pd.merge(test_with_baseline, bart_results, 
                             right_on='transcript', left_on='query_transcript', how='left')
test_with_results = pd.merge(test_with_results, bart_ablation_results,
                             right_on='transcript', left_on='query_transcript', how='left')

In [8]:
test_with_results.head()

,cluster,length (aa),query_gene,query_transcript,seq,amino_acid_seq,median,subject_transcript,average_pident,gene,...,bart30_cross_entropy_loss,bart30_perplexity,bart30_accuracy,transcript,bart30_ablation_prediction,bart30_ablation_entropy,bart30_ablation_num_of_correct_predicted_codons,bart30_ablation_cross_entropy_loss,bart30_ablation_perplexity,bart30_ablation_accuracy
0,2191,932,ENSG00000134324,ENST00000396097,ATGAGCAGAGTGCAGACCATGAATTACGTGGGGCAGTTAGCCGGCC...,MSRVQTMNYVGQLAGQVFVTVKELYKGLNPATLSGCIDIIVIRQPN...,"(expr_pre75_90, expr_pre50_75, expr_pre75_90, ...",ENST00000261596,48.943442,ENSG00000134324,...,1.070715,2.917465,0.508039,ENST00000396097,ATGAGCAGAGTGCAGACCATGAACTATGTGGGGCAGCTGGCTGGCC...,-4106.103027,469,1.070143,2.915796,0.502680
1,5329,249,ENSG00000172456,ENST00000634606,ATGTGGCTGGACCATCGAGCAGTCAGTCAAGTTAACAGGATCAATG...,MWLDHRAVSQVNRINETKHSVLQYVGGVMSVEMQAPKLLWLKENLR...,"(expr_pre25_50, expr_pre25_50, expr_pre25_50, ...",NaN,0.000000,ENSG00000172456,...,1.105201,3.019833,0.464000,ENST00000634606,ATGTGGCTGGACCACAGAGCTGTGTCCCAGGTGAACAGAATCAATG...,-4239.449219,116,1.117450,3.057049,0.464000
2,7096,463,ENSG00000118495,ENST00000416623,ATGGCCACGTTCCCCTGCCAGTTATGTGGCAAGACGTTCCTCACCC...,MATFPCQLCGKTFLTLEKFTIHNYSHSRERPYKCVQPDCGKAFVSR...,"(expr_pre25_50, expr_pre50_75, expr_pre50_75, ...",ENST00000367405,18.618728,ENSG00000118495,...,0.994691,2.703889,0.575431,ENST00000416623,ATGGCCACCTTCCCCTGCCAGCTCTGTGGGAAGACCTTCCTGACCC...,-4101.684570,262,1.007104,2.737661,0.564655
3,7405,432,ENSG00000257950,ENST00000550383,ATGGGGCAGGCGGGCTGCAAGGGGCTCTGCCTGTCGCTGTTCGACT...,MGQAGCKGLCLSLFDYKTEKYVIAKNKKVGLLYRLLQASILAYLVV...,NaN,ENST00000413302,38.319426,ENSG00000257950,...,1.008740,2.742144,0.598152,ENST00000550383,ATGGGCCAGGCTGGCTGCAAAGGCCTCTGCCTGTCTCTCTTTGACT...,-4199.959473,260,0.994005,2.702035,0.600462
4,5500,57,ENSG00000107669,ENST00000690706,ATGGCTTTCTGGGCGGGGGGTTCGCCCAGCGTCGTGGACTATTTCC...,MAFWAGGSPSVVDYFPSEDFYRCGYCKNESGSRSNGMWAHSMTVQD...,NaN,NaN,0.000000,ENSG00000107669,...,1.066228,2.904404,0.517241,ENST00000690706,ATGGCCTTCTGGGCTGGAGGCAGCCCCTCTGTGGTGGACTACTTCC...,-4496.814941,29,1.037383,2.821822,0.500000

In [9]:
test_with_results.drop(columns=['transcript'], inplace=True)

In [10]:
test_with_results['bart30_accuracy'].mean()

np.float64(0.5195381761943917)

In [11]:
test_with_results['bart30_ablation_accuracy'].mean()

np.float64(0.5164021253956869)

In [18]:
test_with_results[test_with_results['median'].isna()]['bart30_ablation_accuracy'].mean()

np.float64(0.5007149278218319)

In [17]:
test_with_results[test_with_results['median'].isna()]['bart30_accuracy'].mean()

np.float64(0.5003107205509641)

# Save Merged Data

**As Pickle**

In [13]:
test_with_results.to_pickle(os.path.join(data_path, '2_test_with_bart30.pkl'))

**As Json CSV**

In [14]:
def convert_to_json_string(value):
    if pd.isna(value):
        return value
    return json.dumps(value)

test_with_results['median'] = test_with_results['median'].apply(convert_to_json_string)
test_with_results['median_float'] = test_with_results['median_float'].apply(convert_to_json_string)

test_with_results.to_csv(os.path.join(data_path, '2_test_with_bart30.json.csv'), index=False)

In [15]:
test_with_results = pd.read_csv(os.path.join(data_path, '2_test_with_bart30.json.csv'))
test_with_results[test_with_results['median'].isna()]['bart30_accuracy'].mean()

np.float64(0.5003107205509641)

In [16]:
test_with_results[test_with_results['median'].notna()]['bart30_accuracy'].mean()

np.float64(0.5250551890026637)